### PR TITLE
[textCurve] Fix setZero

### PR DESCRIPTION
**Pull request by gabrielebndn**
My changes in #13 introduced compilation errors. This fixes them. I tested it with sot-talos-balance.
Ideally, there should be unit tests for this, but I do not have time now (and I do not think it is really worth it because this package will be replaced by curves some time soon)

### CODE REVIEW

**Comment by gabrielebndn** [comment]
@nim65s, you can merge this

**Comment by nim65s** [comment]
This works for me: https://gepgitlab.laas.fr/gsaurel/parametric-curves/pipelines/7673/builds
But maybe we could add a unit test to avoid this issue to happen again, as you prefer.

**Comment by nim65s** [comment]
There is just a slight formating issue:
```
-      std::cout << "Unexpected number of columns (expected " << size << " or " << 2*size << " or " << 3 * size << ", found " << data.cols() << ")\n";
+      std::cout << "Unexpected number of columns (expected " << size << " or " << 2 * size << " or " << 3 * size
+                << ", found " << data.cols() << ")\n";
       return false;
```

**Comment by gabrielebndn** [comment]
> There is just a slight formating issue:
> 
> ```
> -      std::cout << "Unexpected number of columns (expected " << size << " or " << 2*size << " or " << 3 * size << ", found " << data.cols() << ")\n";
> +      std::cout << "Unexpected number of columns (expected " << size << " or " << 2 * size << " or " << 3 * size
> +                << ", found " << data.cols() << ")\n";
>        return false;
> ```

I am not sure about what you mean. I do not have this change in my commit. Do you want me to make it? Or you mean you made it?

**Comment by nim65s** [comment]
You updated this line, and it is now very long (it can't be read on https://github.com/stack-of-tasks/parametric-curves/pull/14/files without scrolling).

This diff is provided by clang-format, which suggest to split it in two lines.

**Comment by gabrielebndn** [comment]
Ok, I'll fix it right away

**Comment by gabrielebndn** [comment]
Fixed

**Comment by nim65s** [comment]
All green :)

**Pull request merged**
